CREATE TABLE `hospedes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(100) NOT NULL,
	`propertyName` varchar(255) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`address` text,
	`rating` int,
	`reviewCount` int,
	`checkInDate` varchar(50),
	`checkOutDate` varchar(50),
	`hospedageValue` int,
	`paymentLink100` text,
	`paymentLink30Pix` text,
	`clientEmail` varchar(320),
	`clientPhone` varchar(20),
	`clientCpf` varchar(20),
	`guestCount` int,
	`detail1` text,
	`detail2` text,
	`detail3` text,
	`roomType` varchar(255),
	`breakfastIncluded` int DEFAULT 0,
	`freeCancellationDate` varchar(50),
	`mainGuestName` varchar(255),
	`photos` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hospedes_id` PRIMARY KEY(`id`),
	CONSTRAINT `hospedes_slug_unique` UNIQUE(`slug`)
);
